---
- hosts: windows
  gather_facts: false

  tasks:
  - name: Run detectPSVersion
    psexec:
        hostname: '{{ansible_host}}'
        connection_username: hccadmin
        connection_password: ServiceP@ss123!
        encrypt: no
        executable: powershell.exe
        arguments: Write-Host $PSVersionTable.PSVersion.ToString()
    delegate_to: localhost
    register: powershell_version
    become_user: System

  - name: Output  
    debug:
      var: powershell_version.stdout_lines