---
- hosts: all
  tasks:
  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
    path: C:\Temp
    state: directory

  - name: Get Splunk Zip
    win_get_url:
     url: "https://5111rsgpwam1pmg1admin.blob.core.usgovcloudapi.net/ansible/splunk/splunk.zip"
     dest: "c:\\temp\\splunk.zip"

  - name: Unzip Splunk
    win_unzip:
     src: "C:\\temp\\ansible"
     dest: "C:\\temp\\ansible"
     delete_archive: yes

  - name: Execute Splunk PowerShell Script
    win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/ansible/splunk/install_splunk_uf_v1.1.0.ps1
    register: splunk_psresult