---
- hosts: windows
  gather_facts: false
  tasks:
  - name: Check whether the host supports encryption
    win_shell: |
        if ([System.Environment]::OSVersion.Version -lt [Version]"6.2") {
            "false"
        } else {
            "true"
        }
    register: encryption_supported_raw
    delegate_to: localhost

  - name: Get PowerShell Version
    win_shell: |
        Write-Host $PSVersionTable.PSVersion.ToString()
    register: powershell_version
    delegate_to: localhost

  - name: Output  
    debug:
        var: powershell_version.stdout_lines
    delegate_to: localhost        