---
- hosts: windows
  gather_facts: false
  tasks:
  - name: Get PowerShell Version
    raw: 'Write-Host $PSVersionTable.PSVersion.ToString()'
    register: powershell_version

  - name: Output  
    debug:
        var: powershell_version.stdout_lines