---
- hosts: windows
  gather_facts: yes
  tasks:
    - include_role:
        name: windows
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }}"
#      when:
#        - ansible_architecture is search("64")

- hosts: linux
  gather_facts: yes
  tasks:
    - include_role:
        name: linux
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }}"        
#      when:
#        - ansible_architecture is search("64")