---
- hosts: windows
  connection: local
  tasks:
    - block:
        - name: Check to see if host is reachable
          wait_for_connection:
            timeout: 10
        - name: Add reachable hosts to win_reachable group
          group_by:
            key: "win_reachable"
        - debug: 
            msg: "Reachable, added to group "            
      rescue:
        - debug: 
            msg: "Unreachable, not added to group "
  
- hosts: win_reachable
  tasks:       
    - include_role:
        name: windows
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }} and reachable"
#      when:
#        - ansible_architecture is search("64")

- hosts: linux
  tasks:
    - include_role:
        name: linux
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }}"        
#      when:
#        - ansible_architecture is search("64")