---
- hosts: windows
  gather_facts: no
  roles:
      - role: windows
        when: ansible_facts['architecture'] is defined
  

- hosts: linux
  gather_facts: no
  roles:
      - role: linux
        when: ansible_facts['architecture'] is defined