---
- name: set specific variables for distributions
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: say something
  debug: msg="foo={{ foo }}"