---
- hosts: windows
  gather_facts: no
  tasks:
    - include_role:
        name: windows
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }}"
  when: ansible_facts['architecture'] is defined

- hosts: linux
  gather_facts: no
  tasks:
    - include_role:
        name: linux
    - debug:
        msg: "System {{ inventory_hostname }} is architecture {{ ansible_architecture }}"
  when: ansible_facts['architecture'] is defined