---
- hosts: windows
  gather_facts: yes
  roles:
      - { role: windows, when: ansible_architecture is defined }
  

- hosts: linux
  gather_facts: yes
  roles:
      - { role: linux, when: ansible_architecture is defined }