---
- hosts: localhost
  tasks:
    - name: Add tower group
      tower_group:
        name: os_Windows
        inventory: "Cloud Servers"
        state: present
        group_by:
            key: os_{{ ansible_distribution }}