---
- hosts: all
  connection: local
  tasks:
    - name: Add tower group
      tower_group:
        name: os_{{ ansible_distribution }}
        inventory: "Cloud Servers"
        state: present
        group_by:
            key: os_{{ ansible_distribution }}