---
## BEGIN Tanium Config
 - name: install-tanium | check to see if tanium is already installed
   stat:
     path: /opt/Tanium/TaniumClient 
   register: taniuminstalled

 - name: install-tanium | download Tanium install rpm
   get_url:
     url: https://5111rsgpwam1pmg1admin.blob.core.usgovcloudapi.net/cloudops/tools/ansible/tanium/Linux/TaniumClient-7.2.314.3211-1.rhe7.x86_64.rpm
     dest: /var/tmp/TaniumClient-7.2.314.3211-1.rhe7.x86_64.rpm
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | wait for Tanium rpm
   wait_for:
     path: /var/tmp/TaniumClient-7.2.314.3211-1.rhe7.x86_64.rpm
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | download Tanium pub
   get_url:
     url: https://5111rsgpwam1pmg1admin.blob.core.usgovcloudapi.net/cloudops/tools/ansible/tanium/Linux/tanium.pub
     dest: /var/tmp/tanium.pub
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | wait for Tanium pub
   wait_for:
     path: /var/tmp/tanium.pub
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | adjust permissions on rpm
   file:
     path: /var/tmp/TaniumClient-7.2.314.3211-1.rhe7.x86_64.rpm
     owner: root
     group: root
     mode: 0755
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | install Tanium
   shell: rpm -i /var/tmp/TaniumClient-7.2.314.3211-1.rhe7.x86_64.rpm
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | copy tainum.pub file to correct folder
   copy:
     src: /var/tmp/tanium.pub
     dest: /opt/Tanium/TaniumClient/tanium.pub
     owner: root
     group: root
     mode: 0755
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | set ServerNameList
   shell: /opt/Tanium/TaniumClient/TaniumClient config set ServerNameList tan1.utc.com,tan2.utc.com,159.82.100.163,159.82.100.164,10.192.73.150,10.192.73.151,xmnp180i.utc.com,xnwp908i.utc.com,167.17.207.189,167.17.223.189,159.82.219.68,167.17.255.189
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | show ServerNameList
   shell: /opt/Tanium/TaniumClient/TaniumClient config get ServerNameList
   when:
     - not taniuminstalled.stat.exists

 - name: install-tanium | Re-start service TaniumClient to set ServerNameList
   service:
     name: taniumclient
     state: restarted
   when: 
     - not taniuminstalled.stat.exists
 
 - name: install-tanium | Start service TaniumClient, if not running always run
   service:
     name: taniumclient
     state: started
## END Tanium Config

 - name: Print some debug information 
   debug: 
      msg: "LINUX | Install Tanium | System {{ inventory_hostname }} has OS {{ansible_distribution}}"   
   tags: debug_info