---
- name: redhat deployment
  import_tasks: redhat.yml
  when: ansible_os_platform|lower == 'redhat'

- name: centos deployment
  import_tasks: centos.yml
  when: ansible_os_platform|lower == 'centos'

  debug: 
    msg: "System {{ inventory_hostname }} has OS {{ansible_distribution}}"   
  tags: debug_info