- name: check-sep | check to see if SEP service is installed
  win_service:
    name: "Symantec Endpoint Protection"
  register: SEP14serviceresult

- name: set_facts
  set_fact:
      key_value: " {{ SEP14serviceresult.results }}" # required. The C(set_fact) module takes key=value pairs as variables to set in the playbook scope. Or alternatively, accepts complex arguments using the C(args:) statement.
      cacheable: true # not required. This boolean indicates if the facts set will also be added to the fact cache, if fact caching is enabled.
  with_items: