---
 - name: install-tanium | check to see if SEP service is installed
   win_service:
     name: "Symantec Endpoint Protection"
   register: SEPserviceresult

 - name: install-tanium | Run Tanium installer
   win_package:
     path: "https://5111rsgpwam1pmg1admin.blob.core.usgovcloudapi.net/cloudops/tools/ansible/tanium/Windows/InstallTanium7.2.314.3211Windows.msi"
     creates_service: "Tanium Client"
     state: present
     arguments: /quiet
   when: SEPserviceresult['exists'] == true

 - name: Print some debug information 
   debug: 
    msg: "Windows | Install Tanium | System {{ inventory_hostname }} has OS {{ansible_distribution}}"   
   tags: debug_info