---
 - name: install-sep | check to see if SEP service is installed
   win_service:
     name: "Symantec Endpoint Protection"
   register: SEP14serviceresult

 - name: install-sep | download SEP 14
   win_get_url:
     url: "https://stautahqm0dg002.blob.core.windows.net/msi/SEP14.zip"
     dest: C:\Temp\SEP14Install_Ver3.3.zip
   when: SEP14serviceresult['exists'] == false

 - name: install-sep | unzip SEP
   win_unzip:
     src: C:\Temp\SEP14Install_Ver3.3.zip
     dest: C:\Temp\SEP14Install
     delete_archive: yes
   when: SEP14serviceresult['exists'] == false

 - name: install-sep | install SEP PW Azure Cloud
   win_command: cscript UTC-ENG-Symantec-Endpoint-Protection-v14.0-RU1-MP2-r1.0.0.vbs /s /imagebuild /r:0 /ForceConfig
   args:
     chdir: 'C:\Temp\SEP14Install\SEP 14 OOS Upgrade r3.3\SEP'
   when:
     - SEP14serviceresult['exists'] == false

 - name: install-sep | remove SEP14 installer folder
   win_file:
     path: C:\Temp\SEP14Install
     state: absent
   when:
     - SEP14serviceresult['exists'] == false
 
 - name: Print some debug information 
   debug: 
       msg: "Windows | Install SEP | System {{ inventory_hostname }} has OS {{ansible_distribution}}"   
   tags: debug_info