---
 - name: Create Temp Directory for logging
   win_file:
     path: c:\Temp
     state: directory

 - name: include tasks
   include: "{{ filename }}.yml"
   loop_control:
     loop_var: filename
   with_items:
     - install-sep
     - install-csp
     - install-tanium
     - install-splunk